
services:
  opend:
    image: ghcr.io/chasenlabs/futu-opend:latest
    #image: ghcr.io/chasenlabs/moomoo-opend:latest # moomoo
    container_name: futu-opend
    restart: unless-stopped
    ports:
      - 11111:11111
    # https://openapi.futunn.com/futu-api-doc/opend/opend-cmd.html#8799
    volumes:
      - ./FutuOpenD.xml:/opend/FutuOpenD.xml
#      - ./OpenD.xml:/opend/OpenD.xml # moomoo
#   or https://openapi.futunn.com/futu-api-doc/opend/opend-cmd.html#465
#    command:
#      - /docker-entrypoint.sh
#      - -login_account=<account number>
#      - -login_pwd_md5=<md5 string>
#      - -api_port=11111
#      - -api_ip=0.0.0.0
#      - -telnet_port=22222
#      - -lang=en
