name: Create Tag


on:
  workflow_dispatch:

  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  hook:
    name: 'Create Tag'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      # get version from last commit message
      - run: |
          commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)"
          echo "version=$(echo $commit_message | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_OUTPUT            

      - name: Create Tag
        if: ${{ steps.hook.outputs.version != '' }}
        uses: jaywcjlove/create-tag-action@v2.2.0
        with:
          tag: ${{ steps.hook.outputs.version }}
