name: Build

on:
  push:
    branches:
      - master

  workflow_dispatch:


permissions:
  contents: read
  id-token: write
  packages: write


jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
          group: ${{ github.workflow }}-${{ github.ref }}-build
          cancel-in-progress: true

        steps:
        - uses: actions/checkout@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/${{ github.repository }}
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=raw,value=${{ github.run_id }}
              type=raw,value=latest

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: |
                org.opencontainers.image.title=futu-opend
                org.opencontainers.image.description=The futu-opend image
                org.opencontainers.image.source=github.com/${{ github.repository }}
